name: Test-Job
on:
  workflow_dispatch: 
    branches:
    - readne-edits
jobs:
  check-bats-version:
    if: contains( github.ref, 'readne-edits')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: apt-get update -y && test -d ~/.ssh || mkdir ~/.ssh && chmod 700 ~/.ssh && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config && chmod 600 ~/.ssh/config
      - run: mkdir ~/bin && curl https://raw.githubusercontent.com/git-ftp/git-ftp/master/git-ftp > ~/bin/git-ftp
      - run: chmod +x ~/bin/git-ftp
      - run: git config --global user.email "marshgamer007@gmail.com"
      - run: git config --global user.name "marshgamer007@gmail.com"
      # Use git-ftp to copy all the files to the server, while keeping the connections
      #- run: git ftp init --user $USER_NAME --passwd $PASSWORD sftp://$SERVER-URL:22/home/test/ -vv
      - run: git ftp push --user $USER --passwd "$PASSWORD" "sftp://$SERVER-URL:22/" -f
